### ISSUE TITLE
Broken code due to mismatching return value count in dataset generation

### ISSUE THREAD

**Issue by patham9** [bowen-xu/SeL-NAL#1]
I found your writing interesting so wanted to run the code.
However this code cannot work as generate_dataset in dataset.py returns 3 variables, while all calls in the test scripts expect 2.
Any ideas?

**Comment by bowen-xu** [comment]
`test_capacity.py` and `test_catastrophic_forgetting.py` are outdated. I haven't updated them. For the moment, you may play `tests.ipynb` and enjoy.

**Comment by bowen-xu** [comment]
@patham9 I just modified the codes. Let me know if they work now.
